sudo: false
language: node_js
node_js:
  - '6'

cache:
  directories:
  - node_modules

script:
  - npm test
  - npm run lint
  - npm run coverage

after_success:
  # Report coverage to coveralls.io
  - npm run coveralls
  - rm -rf ./coverage
  - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
