sudo: false
language: node_js
node_js:
- '4.2'
- node
matrix:
  allow_failures:
    - node_js: node

cache:
  directories:
  - node_modules

script:
  - npm test
  - npm run lint
  - npm run coverage

after_success: 'npm run coveralls'
